### ISSUE TITLE
Callback Error when looking for homebridge

### ISSUE THREAD

**Issue by iDevo** [jamesblanksby/homebridge-gpio#4]
Hi there!
I've a tiny issue when homebridge is already running on my RaspberryPi 2 and then looking for new accessories.
It occurs a crash due to a multiple times called callback function but I'm unsure, whether this is a homebrige issue or a homebridge-gpio issue (which is by the way the only plugin which is installed yet). Due to the first exception I'd say rather homebridge than the plugin. 
I found the[ issue 296](https://github.com/nfarina/homebridge/issues/296) which is kind of similar but doesn't provide a solution in my opinion. 

Reproducing steps:

1. Make sure you've installed [Apple's HomeKit Catalog App](https://developer.apple.com/library/ios/samplecode/HomeKitCatalog/Introduction/Intro.html) and you've added a home including the gpio accessories.
2. Close the App completely
3. Starting homebridge with homebridge-gpio installed
4. Open HomeKit Catalog (HMCatalog)
5. This crash will be displayed:

[Sun May 01 2016 20:02:18 GMT+0000 (UTC)] Homebridge is running on port 51826.

--- _Starting iOS-App to look for new accessories_ ---

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at /usr/local/lib/node_modules/homebridge-gpio/index.js:35:9
    at ReadFileContext.callback (/usr/local/lib/node_modules/homebridge-gpio/node_modules/pi-gpio/pi-gpio.js:173:38)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)

Is it possible that I've misconfigured something, which leads to this crash?

**Comment by RicardoRobinson** [comment]
Remove the "description" line, it worked for me

**Comment by mateuspok** [comment]
Same problem here, other accessories load normally, when I try to load gpio on Apple Homekit gives me the error.

**Comment by AndreasPrang** [comment]
I'm getting the same error. After removing 35. It's not longer crashing, but (as expected) not working...

**Comment by AndreasPrang** [comment]
The following version is running without the correct status. it might be a problem with the anonymous function inside the prototype ?

```
GPIOAccessory.prototype.getOn = function(callback) {
    this.log(gpio);
    callback(null, true);             // working alternative outside the gpio.read function

/*
    gpio.read(this.pin, function(err, value) {
        if (err) callback(err);
        var on = value;
        callback(null, on);
    });
*/
}

```

**Comment by AndreasPrang** [comment]
err was not null. So the callback block was called twice. I will create a pull request.

**Comment by jamesblanksby** [comment]
Published - @AndreasPrang thank you for your bugfix
